[book]
title = "2025 CompClub Spring Workshops Handbook"
author = "2025 CompClub Internals & SecSoc Education Team"
language = "en"


[build]
build-dir = "book"

[output.html]
default-theme = "scifi"
additional-css = ["theme/custom.css"]

[preprocessor.callouts]